### PR TITLE
Added maybe color correction and definitely model changing

### PR DESCRIPTION
**Pull request by Brennan-VanderLaan**
This plugin is wicked.

The first commit was auto-formatting from Pycharm (sorry!)
The second commit has the actual changes, I added in badly tested color correction toggling and well tested model changing :D

I also made the UI show you an example of what to use for the new format including the model name you started the webui with. It's meh, but it's a start :D

### CODE REVIEW

**Comment by Brennan-VanderLaan** [comment]
Feel free to ignore it, I'm working with this plugin and thought I'd kick back the changes I've been making as I go.

https://cdn.discordapp.com/attachments/1027657999495471124/1030289647147954197/20221013211243.gif

That's an example of using 4 models to render a single clip.

**Comment by Animator-Anon** [comment]
Cool, thanks for the contribution! Let me have a gander.

**Comment by Animator-Anon** [comment]
I think I can roll these changes into the v2 script. One question, is how to set the model back to what it was if you change it?
Looks like it stays changed, which will mess up a second generation (unless you specify at frame 0 what the starting model should be).

**Comment by Brennan-VanderLaan** [comment]
Oh you're totally right - I can fix that

**Pull request closed without merging**
