### PR TITLE
Prompt interpolation: an approach to reduce img2img embossing

### PR DESCRIPTION
**Pull request by jeffgyf**
The basic idea is, for the intermediate frames, instead of using previous key frame prompt and denoise on the previous processed image, the better idea is using [emphasis](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#attentionemphasis) to generate the intermediate prompt of previous and next key frame prompt and denoising on the same image generated for last key frame.

### CODE REVIEW

**Comment by jeffgyf** [comment]
figure out that the emphasis mechanism is not ideal, closing the PR

**Comment by Animator-Anon** [comment]
Another implementation has been posted, using a built-in prompt weighting feature I didn't know about. I an working that currently., Thanks for the input!

**Comment by jeffgyf** [comment]
> Another implementation has been posted, using a built-in prompt weighting feature I didn't know about. I an working that currently., Thanks for the input!

After multiple experiments, I figured out that the sum of the factors of all subprompt concated by `AND` has to be 1, otherwise the output will look bad. That's why I didn't find prompt emphasis work well. Another suggestion is the denoise strength gradient between keyframe, which will make the transition from input image to keyframe become smooth.

Besides, I believe intergrating the [FILM](https://github.com/google-research/frame-interpolation) project to use it as frame transition solution which can make the generated video looks much better.

**Comment by Animator-Anon** [comment]
I think in my case, there will only be two groups AND together, and they should = 1. The templates and prompts are already concatenated by this time.
Mostly at this stage I haven't done much with denoising strength, kept it constant. Do you mean a smooth transition from one to the other, or a reduction in the middle? The implantation another user provided kept it a smooth transition from one to the other, and a reduced value if both prompts are the same.

**Pull request closed without merging**
